### ISSUE TITLE
Calculate signature over proto payload

### ISSUE THREAD

**Issue by mikehelmick** [eu-federation-gateway-service/efgs-federation-gateway#196]
## Feature description

Allow for calculation and verification over the serialized protocol buffer rather than the custom packed binary format.

## Problem and motivation

The packed binary format is dependent on sorting and specific endian encoding which can lead to implementation issues across different programming languages.

When already producing a binary upload format (i.e. protocol buffers), this also requires building 2 complete representations in memory at the same time.

Allowing verification of the signed proto payload will allow for this data not to need to be transformed to verify the signature.

This will make verification 

1. less error prone: no custom binary packing and no sorting needed

2. more efficient by not needing to build parallel data structures containing the same data

## Is this something you're interested in working on

Yes

**Comment by SchulzeS** [comment]
The Architecture defines the Support of JSON and ProtoBuf, with an option for other formats. This has to be discussed.

Option1: Change of the singature calculation in this way means to drop the JSON Support and the Support for all other formats in the future. All MS have to switch their backends to accept/content-type application/protobuf=2.0 which uses SHA256 over the protobuf wire.

Option 2: it's discussable to remove the format conversion. Currently is an upload in protobuf and a download in JSON possible. After removing the format conversion option, an upload in protobuf, means download in protobuf. (More effort in backwards compatbility, because all formats have to be checked)

@alstiefel and @joerg-oppermann-tsi  The Customer and the MS have to decide here for this breaking architecture change and how they wanna proceed with this.

**Comment by cascremers** [comment]
I strongly support this suggestion [esp. in @SchulzeS 's option 1 form], and this is also what CISPA proposed in internal discussions many weeks ago.
Besides the obvious backwards compatibility break, the only minor extra effort I can see is if there is any national backend currently uploading in JSON format.

With respect to efficiency and complexity: for each upload batch, this would save on three instances of conversions and key sorting steps (one time at the uploader, one at the EFGS, and one at the auditing step of a national backend). It would also substantially simplify the auditing procedure (esp for multiple uploads of one MS within one batch period), as one would create a clearer binding between upload batch and signature.

For the national backends (if there are any) that currently use json upload/download, this would require them to convert json to protobuf and vice versa, which seems more straightforward than the current signature calculation.

This would possibly even allow to shift to "upload batch" as the stored data unit, further simplifying the design. One can still perform the same checks over the keys contained in the upload batch of course.

**Comment by solita-alperttiti** [comment]
What is the current status of this issue? Would this be done in some point or is there even some estimate when this enhancement would arrive?

Anyway, I highly upvoting @SchulzeS option 1.
